source 'https://rubygems.org'
ruby '2.3.1'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'carrierwave', '~> 1.0'
gem 'ckeditor', '4.1.3'
gem 'cloudinary'
gem 'devise'
gem 'faker', '~> 1.7'
gem 'figaro'
gem 'font-awesome-sass'
gem 'fontello_rails_converter'
gem 'friendly_id', '~> 5.1.0'
gem 'gibbon'
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'pg'
gem 'puma'
gem 'pundit', '~> 1.1'
gem 'rails_admin', '>= 1.0.0.rc'
gem 'rails-i18n', '~> 5.0.0'
gem 'rails', '5.0.1'
gem 'raygun4ruby'
gem 'redis'
gem 'remotipart', github: 'mshibuya/remotipart'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'validates_email_format_of'
gem 'vemv', github: 'vemv/vemv', ref: '2df6eeed573bb52c5fc02fc60e1e5e75988b66df'

group :development, :test do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'factory_girl_rails'
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'rubocop', '~> 0.48.1'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'spring'
  gem "letter_opener"
end

group :test do
  gem 'capybara', '~> 2.11'
  gem 'database_cleaner', '~> 1.5'
  gem 'launchy', '~> 2.4'
  gem 'rails-controller-testing', '~> 1'
  gem 'rspec-rails', '~> 3.5'
  gem 'rspec-retry', '~> 0.5'
  gem 'selenium-webdriver', '~> 2.47'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'simplecov', '~> 0.12', require: false
  gem 'timecop', '~> 0.8'
  gem 'webmock', '~> 2.3'
end


